// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMSwem1rrl4hwUMtUHE18milu7rr8LdZY',
    appId: '1:1033583464739:web:4043262fd4b4f98b86fc96',
    messagingSenderId: '1033583464739',
    projectId: 'valorantinfo-e6bd9',
    authDomain: 'valorantinfo-e6bd9.firebaseapp.com',
    storageBucket: 'valorantinfo-e6bd9.firebasestorage.app',
    measurementId: 'G-BFNB2LTN7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAr3JlpZN-4RuL3OVrHrjqfUrNLq5r4mw',
    appId: '1:1033583464739:android:171767552e53609686fc96',
    messagingSenderId: '1033583464739',
    projectId: 'valorantinfo-e6bd9',
    storageBucket: 'valorantinfo-e6bd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOoRiuSLm2ScUmSlz1IjO5Z4vyheIwoo8',
    appId: '1:1033583464739:ios:47d6ae012ab6c34986fc96',
    messagingSenderId: '1033583464739',
    projectId: 'valorantinfo-e6bd9',
    storageBucket: 'valorantinfo-e6bd9.firebasestorage.app',
    iosBundleId: 'com.example.valorantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOoRiuSLm2ScUmSlz1IjO5Z4vyheIwoo8',
    appId: '1:1033583464739:ios:47d6ae012ab6c34986fc96',
    messagingSenderId: '1033583464739',
    projectId: 'valorantinfo-e6bd9',
    storageBucket: 'valorantinfo-e6bd9.firebasestorage.app',
    iosBundleId: 'com.example.valorantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMSwem1rrl4hwUMtUHE18milu7rr8LdZY',
    appId: '1:1033583464739:web:d8e4289986c30fbc86fc96',
    messagingSenderId: '1033583464739',
    projectId: 'valorantinfo-e6bd9',
    authDomain: 'valorantinfo-e6bd9.firebaseapp.com',
    storageBucket: 'valorantinfo-e6bd9.firebasestorage.app',
    measurementId: 'G-91S603BH01',
  );
}
